### ISSUE TITLE
Error using .SubNodes

### ISSUE THREAD

**Issue by MikhailKrasnobaev** [hylasoft-usa/h-opc#13]
Hi.
For some reason I can't find the description for .SubNodes in the code. 
Already tried manually adding everything from your project, as well as installing Nuget package.

Thank you in advance for the reply.

**Comment by itajaja** [comment]
You are right! That was an API until 0.3.1, in 0.4 you should use either `IEnumerable<TNode> ExploreFolder(string tag)` or `Task<IEnumerable<Node>> ExploreFolderAsync(string tag);`.
This was done in order to accomodate for asynchronous APIs. I will update the README accordingly. Let me know if this answers your question, so I can close this issue

**Comment by itajaja** [comment]
I updated the readme, let me know if you have any further question :)

**Comment by MikhailKrasnobaev** [comment]
Thanks a lot! 
I only started working with KepwareEx, still trying to connect to it.
In the next few days I will give a feedback for sure.

**Comment by itajaja** [comment]
Glad it worked :)
